### ISSUE TITLE
Timeout while requesting MIoT api /home/device_list

### ISSUE THREAD

**Issue by Seifon** [AlexxIT/XiaomiGateway3#828] opened 2022-09-17 06:19 UTC
启动HA，报这个错误：

Timeout while requesting MIoT api /home/device_list

**Comment by rezmus** [comment] 2022-09-23 14:13
/v2/home/device_list_page

**Comment by bobofruit1970** [comment] 2022-09-23 16:52
The same for me:
2022-09-23 18:40:43.121 ERROR (MainThread) [custom_components.xiaomi_gateway3.core.xiaomi_cloud] Timeout while requesting MIoT api /home/device_list

Every few days the same error.

**Comment by vit-um** [comment] 2022-11-12 12:26
The same problem: 

Logger: custom_components.xiaomi_gateway3.core.xiaomi_cloud
Source: custom_components/xiaomi_gateway3/core/xiaomi_cloud.py:119
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: 14:11:09 (2 occurrences)
Last logged: 14:11:09

Timeout while requesting MIoT api /v2/home/device_list_page

**Comment by AlexxIT** [comment] 2022-11-15 19:41
`/home/device_list` - is old API version. Fixed in latest release.
`/v2/home/device_list_page` - caused by connection problems to the Chinese cloud and cannot be fixed

**Closed by AlexxIT** 2022-11-15 19:41 UTC
Labels: enhancement
