### ISSUE TITLE
Sonoff MS01 SNZB-03 motion sensor state (occupancy entity)

### ISSUE THREAD

**Issue by minskmail** [AlexxIT/XiaomiGateway3#738] opened 2022-04-25 18:48 UTC
Hi, it looks like Sonoff MS01 SNZB-03 motion sensor doesnt work properly
after pairing with gateway occupancy entity created successfully, but it never change it state to on (always off). In zigbee2mqtt addon same entity of this sensor works well.

**Comment by WarC0zes** [comment] 2022-04-26 03:37
Same problem with sonoff SNZB-04 and SNZB-01 on gateway ZNDMWG03LM, not state change.
Not problem with ZHA and Sonoff Zigbee 3.0 USB Dongle, state change ok . 
The problem is since core 2022.4.x.

**Comment by AlexxIT** [comment] 2022-05-01 09:22
Fixed on latest master-version

**Closed by AlexxIT** 2022-05-01 09:22 UTC
Labels: bug

**Comment by WarC0zes** [comment] 2022-05-02 16:22
Thanks, it works wonderfully.
