### ISSUE TITLE
Fix BLE unavailable with Xiaomi Black Hub in the account

### ISSUE THREAD

**Issue by maxmib** [AlexxIT/XiaomiGateway3#975] opened 2023-02-09 15:06 UTC
Device   Xiaomi Multimode Gateway CN
     Firmware  v1.5.4_0090
     Xiaomigateway3 version  tried  v3.1.0 and master
     Homeassistant version   2023.1.7 
  All ble sensors under my Xiaomi Multimode Gateway  becomes unavailable after I upgraded gateway version to v1.5.4_0090. But mesh devices and zigbee devices work  well.Those ble sensors are LYWSD03MMC, RTCGQ02LM,MCCGQ02HL, MJYD02YL-A which used to work well before upgrade. In my network there is also a xiaomi.gateway.hub1(ZSWG01CM ) works as the main gateway.And these devices above all work well in xiaomi official app.

**Comment by AlexxIT** [comment] 2023-02-10 04:05
You need to collect debug logs

**Comment by maxmib** [comment] 2023-02-10 05:20
[xiaomi_gateway3.log](https://github.com/AlexxIT/XiaomiGateway3/files/10703908/xiaomi_gateway3.log)
this is debug log. it seems that no ble sensors' data reveived .
@AlexxIT

**Comment by vmannoor** [comment] 2023-02-10 07:41
simlar to https://github.com/AlexxIT/XiaomiGateway3/issues/972#issue-1572587788, try downgrading to 3.0.0, it worked for me.

**Comment by maxmib** [comment] 2023-02-10 08:16
> simlar to https://github.com/AlexxIT/XiaomiGateway3/issues/972#issue-1572587788, try downgrading to 3.0.0, it worked for me.

Thanks.Tried downgrading, unfortunately,it  didn't work.Ble sensors are still unavailable.

**Comment by AlexxIT** [comment] 2023-02-10 08:58
There is no any BLE data in your logs. Do you have black Xiaomi gateway?

**Comment by maxmib** [comment] 2023-02-10 09:09
> There is no any BLE data in your logs. Do you have black Xiaomi gateway?

Black xiaomi gateway ?Do you mean xiaomi gateway hub which only works with Bluetooth devices ?It  is black and can work as the main gateway.I do have one in my network.

**Comment by AlexxIT** [comment] 2023-02-10 18:12
Other users said that black gateway block BLE data for white gateways

**Comment by maxmib** [comment] 2023-02-11 03:01
> Other users said that black gateway block BLE data for white gateways

In xiaomi official app,it shows that some ble sensors are under white multimode gateway .But those  ble sensors didn't show up in xiaomigateway3 plugin.So I think it's uncertain whether black gateway blocking ble data .

**Comment by pnagy** [comment] 2023-02-14 12:00
@AlexxIT  Same here. I have a white gateway, looks like the first 2023.x HA update broke something because I can't make the BLE sensors available in HA since then. They appear and available in the Mi Home app.

**Comment by sumsethan** [comment] 2023-02-15 01:20
Same problem here 
Mulitmode gateway 1 (after fw 1.5.4)and multimode gateway 2 will act as sub-gateways if a hub gateway (black) presents in a same subnet ,then BLE devices will become unavaliable in Hass.
Tried downgrade multimode gateway 1 back to fw 1.5.1,some BLE devices can show up (but gw1 is not that stable in my home)
here's the hub gateway
https://xiaomipedia.com/en/p/xiaomi-hub-gateway/
Hope its helpful

**Comment by AmigoDen** [comment] 2023-02-18 11:34
@AlexxITI I have a white gateway (FW 1.5.1_0032), after updating 2023.x HA something broke, after that BLE sensors are not available in HA (sometimes after some actions, they become available for a short time - 1-3 hours). At the same time sensors are available in Mi Home app.

**Comment by oimag** [comment] 2023-02-27 06:25
@maxmib I have the same issue, if you disconnect the balck gateway ZSWG01CM, then everything comes back to normal, not sure ZSWG01CM blocks the data but it's the cause.

**Comment by Wh1terat** [comment] 2023-03-16 13:59
Exactly the same issue as others.

- MGL03 (was running 1.5.0_0102, have also tried upgrading to 1.5.4_0090)
- Issues started after upgrade to Home Assistant 2023.3.x and Plugin 3.1.0
- - Prior to this it has been working for nearly 1.5 years without a problem, following frequent upgrades.
- Only used for BLE devices.
- No other Hub devices on the network.

I have tried downgrading with no luck.
When restarting hass, it does come back for a short time.

<img width="1527" alt="Screenshot 2023-03-14 at 17 32 38" src="https://user-images.githubusercontent.com/1288525/225640263-59632e0d-e4ca-4be8-bb70-f2fb3a8f0775.png">

**Comment by Wh1terat** [comment] 2023-03-16 14:34
Mystery solved!

Despite having had it disabled since I purchased it, the ble gateway function magically has been turned on on my qingping air monitor lite.

I rarely open the Xiaomi app or perform firmware updates (If it's not broken, why fix it?) so can only assume that this change has been pushed by Xiaomi without my permission.

**Comment by pnagy** [comment] 2023-03-16 14:38
@Wh1terat Is there any possible solution for the rest of us? I mean I don't have an air monitor only bl motion sensors? Any tip what I should check?

**Comment by Wh1terat** [comment] 2023-03-16 14:43
Looks like there's a couple of different devices that can act as a ble gateway (Who'd have thought my wifi air monitor could?! )

I'd say just to double check within the Xiaomi app (for all regions you have devices) that there aren't any extra devices.

<img width="436" alt="Screenshot 2023-03-16 at 14 42 37" src="https://user-images.githubusercontent.com/1288525/225652959-06627768-f4d6-4100-a8fd-5b983dd7246c.png">

**Comment by pnagy** [comment] 2023-03-30 15:31
@Wh1terat Unfortunately in my case there's nothing there. :(

@AlexxIT Any chance that this can be fixed somehow?

**Comment by AlexxIT** [comment] 2023-04-08 15:29
@maxmib well, your problem will be fixed in next release.

This devices (in the one user account) will select only one main hub for transmit BLE/Mesh data:

- Xiaomi Multimode Gateway fw 1.5.4 (gw3)
- Xiaomi Multimode Gateway 2
- Xiaomi Hub (black)

It will always prefer black hub.

But next integration release has patch for this situation

**Comment by maxmib** [comment] 2023-04-09 04:48
@AlexxIT Great news ! Can't wait to try the new release.

**Comment by AlexxIT** [comment] 2023-04-09 05:02
Changes already in master version. You can test it right now

**Comment by maxmib** [comment] 2023-04-09 06:04
> Changes already in master version. You can test it right now

After changing to master version, the problem is still. Any additional operation required ?

**Comment by AlexxIT** [comment] 2023-04-09 15:25
Integration uses only local connection to gateway.

**Comment by AlexxIT** [comment] 2023-04-13 09:48
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.2.0

**Closed by AlexxIT** 2023-04-13 09:48 UTC
Labels: bug
