### ISSUE TITLE
With v3.3.5, all BLE Mesh bulbs are ON/OFF only, no brightness settings anymore

### ISSUE THREAD

**Issue by Stooovie** [AlexxIT/XiaomiGateway3#1261] opened 2024-01-08 20:14 UTC
After updating to v3.3.5, all my Xiaomi BLE Mesh (M2 YLDP25YL) bulbs now lack brightness settings. Only On/Off. That's a big issue.

Downgrading to 3.3.4 does fix the issue.

**Comment by chertvl** [comment] 2024-01-08 20:43
Duplicate of https://github.com/AlexxIT/XiaomiGateway3/issues/1254

**Comment by kolegych** [comment] 2024-01-10 09:53
You can locally apply changes as in that MR https://github.com/AlexxIT/XiaomiGateway3/pull/1256

**Comment by tianzhuang55** [comment] 2024-01-11 02:54
same here, looking forward to updates.
Thanks always to the contributors! Greeeeeeeat project!

**Comment by sergiogazprom** [comment] 2024-01-18 19:24
Подтверждаю, у меня такая же история. Ждем обновления и спасибо за проект!

**Comment by AlexxIT** [comment] 2024-01-19 06:59
https://github.com/AlexxIT/XiaomiGateway3/issues/1254

**Closed by AlexxIT** 2024-01-19 06:59 UTC
Labels: duplicate
