### ISSUE TITLE
All bluetooth devices become unavailable

### ISSUE THREAD

**Issue by LokiUA** [AlexxIT/XiaomiGateway3#1247] opened 2023-12-29 12:52 UTC
After upgrading to Core 2024.1.0b0-2024.1.0b2 all bluetooth devices become unavailable.
All works well on 2023.12.4

Possible reasons (from release notes):

- Bump bluetooth-data-tools to 0.19.0
- Update habluetooth to 2.0.0
- Bump bluetooth-adapters to 0.16.2
- Bump bluetooth libraries
- Relocate base Bluetooth scanner code into an external library
- Move local bluetooth scanner code into habluetooth library
- Relocate Bluetooth manager to habluetooth library

**Comment by zc1342303** [comment] 2023-12-30 01:04
Same as me.

**Comment by TrongLeNT** [comment] 2024-01-02 04:44
Same as me.

Anyone to help please!

**Comment by eruisi** [comment] 2024-01-03 23:59
I ran into same issue after I upgrade HA core to 2024.1.0
My Xiaomi gateway firmware version is 1.5.6_00001

**Comment by alex-msk** [comment] 2024-01-04 03:38
This message appeared in the logs after the update for 2024.1

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_gateway3/sensor.py", line 42, in <module>
    "power": POWER_WATT,
             ^^^^^^^^^^
NameError: name 'POWER_WATT' is not defined 
```

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_gateway3/climate.py", line 14, in <module>
    HVAC_MODE_OFF: CURRENT_HVAC_OFF,
    ^^^^^^^^^^^^^
NameError: name 'HVAC_MODE_OFF' is not defined

```

**Comment by dengi76** [comment] 2024-01-04 04:36
Same problem!

**Comment by alex-msk** [comment] 2024-01-04 06:48
<details><summary>Details</summary>
<p>



</p>
</details> 

> Same problem!

**Comment by randybb** [comment] 2024-01-04 09:47
duplicate of https://github.com/AlexxIT/XiaomiGateway3/issues/1245

**Closed** 2024-01-05 09:22 UTC
Labels: duplicate
