### ISSUE TITLE
Exception importing custom_components.xiaomi_gateway3.climate (With latest version of Home Assistant)

### ISSUE THREAD

**Issue by terenceng81** [AlexxIT/XiaomiGateway3#906] opened 2023-01-05 14:59 UTC
I have this error with the latest version of Home Assistant, not sure what is the issue, thanks.

Error in the Notification
========================================
Invalid config
The following integrations and platforms could not be set up:

Home Assistant Version
========================================
Home Assistant 2023.1.0
Supervisor 2022.12.1
Operating System 9.4
Frontend 20221213.1 - latest

Error Log
========================================
xiaomi_gateway3.climate ([Show logs](https://hassos.nhkclouds.com/config/logs?filter=xiaomi_gateway3.climate))
Please check your config and [logs](https://hassos.nhkclouds.com/config/logs).

Detailed Error Log
========================================
Unable to prepare setup for platform xiaomi_gateway3.climate: Platform not found (Exception importing custom_components.xiaomi_gateway3.climate).
22:42:36 – (ERROR) setup.py
Unexpected exception importing platform custom_components.xiaomi_gateway3.climate
22:42:36 – (ERROR) Xiaomi Gateway 3 (custom integration)

**Comment by randybb** [comment] 2023-01-05 15:16
another duplicate of #899 
Next time please use search first...

**Comment by terenceng81** [comment] 2023-01-05 15:29
thanks

**Closed** 2023-01-05 15:28 UTC
