### ISSUE TITLE
climate error

### ISSUE THREAD

**Issue by Algorithm0** [AlexxIT/XiaomiGateway3#907] opened 2023-01-05 20:58 UTC
Эта ошибка возникла в кастомной интеграции.

Logger: homeassistant.loader
Source: custom_components/xiaomi_gateway3/climate.py:39
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: 23:25:41 (2 occurrences)
Last logged: 23:53:20

Unexpected exception importing platform custom_components.xiaomi_gateway3.climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 744, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 761, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_gateway3/climate.py", line 32, in <module>
    class XiaomiClimate(XEntity, ClimateEntity):
  File "/config/custom_components/xiaomi_gateway3/climate.py", line 39, in XiaomiClimate
    _attr_temperature_unit = TEMP_CELSIUS
NameError: name 'TEMP_CELSIUS' is not defined

**Comment by Algorithm0** [comment] 2023-01-05 21:01
This error appeared after updating the Home Assistant Core to version 2023.1.0.

**Comment by Algorithm0** [comment] 2023-01-05 21:03
This error appeared after updating the Home Assistant Core to version 2023.1.0.

Here is the second message in the logs:

Logger: homeassistant.setup
Source: setup.py:340
First occurred: 5 января 2023 г., 23:25:41 (2 occurrences)
Last logged: 5 января 2023 г., 23:53:20

Unable to prepare setup for platform xiaomi_gateway3.climate: Platform not found (Exception importing custom_components.xiaomi_gateway3.climate).

**Comment by Algorithm0** [comment] 2023-01-05 21:03
This error appeared after updating the Home Assistant Core to version 2023.1.0.

Here is the second message in the logs:

Logger: homeassistant.setup
Source: setup.py:340
First occurred: 5 января 2023 г., 23:25:41 (2 occurrences)
Last logged: 5 января 2023 г., 23:53:20

Unable to prepare setup for platform xiaomi_gateway3.climate: Platform not found (Exception importing custom_components.xiaomi_gateway3.climate).

**Comment by ALERTua** [comment] 2023-01-06 08:07
full error log:
```
Unable to prepare setup for platform xiaomi_gateway3.climate: Platform not found (Exception importing custom_components.xiaomi_gateway3.climate).

Unexpected exception importing platform custom_components.xiaomi_gateway3.climate

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 744, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 761, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_gateway3/climate.py", line 32, in <module>
    class XiaomiClimate(XEntity, ClimateEntity):
  File "/config/custom_components/xiaomi_gateway3/climate.py", line 39, in XiaomiClimate
    _attr_temperature_unit = TEMP_CELSIUS
NameError: name 'TEMP_CELSIUS' is not defined
```

**Comment by randybb** [comment] 2023-01-06 10:15
duplicate of #899

**Closed** 2023-01-09 07:29 UTC
Labels: duplicate, invalid
