### ISSUE TITLE
HA 2024.1 Issue

### ISSUE THREAD

**Issue by const2github** [AlexxIT/XiaomiGateway3#1250] opened 2024-01-04 08:22 UTC
After update to HA 2024.1 XiaomiGateway3 component is totally broken.

```
Unable to prepare setup for platform 'xiaomi_gateway3.sensor': Platform not found (Exception importing custom_components.xiaomi_gateway3.sensor).
Unable to prepare setup for platform 'xiaomi_gateway3.climate': Platform not found (Exception importing custom_components.xiaomi_gateway3.climate).

```

```
Unexpected exception importing platform custom_components.xiaomi_gateway3.climate

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_gateway3/climate.py", line 14, in <module>
    HVAC_MODE_OFF: CURRENT_HVAC_OFF,
    ^^^^^^^^^^^^^
NameError: name 'HVAC_MODE_OFF' is not defined
```

```
Unexpected exception importing platform custom_components.xiaomi_gateway3.sensor

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_gateway3/sensor.py", line 42, in <module>
    "power": POWER_WATT,
             ^^^^^^^^^^
NameError: name 'POWER_WATT' is not defined
```

Also such warnings:

```
SUPPORT_ALARM_ARM_AWAY was used from xiaomi_gateway3, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_AWAY instead, please create a bug report at https://github.com/AlexxIT/XiaomiGateway3/issues
SUPPORT_ALARM_ARM_HOME was used from xiaomi_gateway3, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_HOME instead, please create a bug report at https://github.com/AlexxIT/XiaomiGateway3/issues
SUPPORT_ALARM_ARM_NIGHT was used from xiaomi_gateway3, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_NIGHT instead, please create a bug report at https://github.com/AlexxIT/XiaomiGateway3/issues
SUPPORT_ALARM_TRIGGER was used from xiaomi_gateway3, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.TRIGGER instead, please create a bug report at https://github.com/AlexxIT/XiaomiGateway3/issues
```

**Comment by GeoViljoen** [comment] 2024-01-04 09:33
I can confirm the issue, rolled back my HA installation..

**Comment by randybb** [comment] 2024-01-04 09:47
duplicate of https://github.com/AlexxIT/XiaomiGateway3/issues/1245

**Comment by Sheredeka** [comment] 2024-01-04 13:54
I can confirm this issue, my log added
[home-assistant_xiaomi_gateway3_2024-01-04T13-50-11.420Z.log](https://github.com/AlexxIT/XiaomiGateway3/files/13830477/home-assistant_xiaomi_gateway3_2024-01-04T13-50-11.420Z.log)

**Comment by petrotti77** [comment] 2024-01-04 14:09
Verrà risolto questo problema?

**Comment by Ivanant1982** [comment] 2024-01-04 14:37
такая же проблема. Откатил систему на предыдущую версию, новую проигнорил, и шлюз подцепился без проблем.

**Comment by sakon63** [comment] 2024-01-04 16:19
Та же проблема после обновления на HA 2024.1

**Comment by gcshum** [comment] 2024-01-04 17:19
I confirmed that HA Core 2024.1.0 broke my Xiaomi Gateway 3 integration. Rolling back to Core 2023.12.4 works again. Please fix so that we can keep HA up to date.

**Comment by Tixio79** [comment] 2024-01-04 18:59
Anche a me, dopo aggiornamento, di è bloccato tutto.
![Screenshot_2024-01-04-09-46-10-694_io homeassistant companion android](https://github.com/AlexxIT/XiaomiGateway3/assets/103521173/b77a6e13-110b-488c-ad83-c7606cacfa88)

**Comment by Mategm** [comment] 2024-01-04 19:11
I can confirm the issue, My HA does drop errors on Xiaomi Gateway 3.

**Comment by Sheredeka** [comment] 2024-01-04 19:15
Go to https://github.com/AlexxIT/XiaomiGateway3/issues/1245#issuecomment-1876994323

And run patch

**Comment by jeremysherriff** [comment] 2024-01-05 06:19
The patch has been merged and is available as part of the `master` branch.

To install it formally, use the "**Redownload**" option in the 3-dot menu in the HACS web interface:
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/1082213/c81d9ec3-0625-4cae-9a31-342ec02b9f1d)

..and choose `master` (**not** v3.3.4). 
Once downloaded, you will need to restart HA for the changes to take effect.

**Comment by avihome63** [comment] 2024-01-05 06:26
> The patch has been merged and is available as part of the `master` branch.
> 
> To install it formally, use the "**Redownload**" option in the 3-dot menu in the HACS web interface: ![image](https://private-user-images.githubusercontent.com/1082213/294408275-c81d9ec3-0625-4cae-9a31-342ec02b9f1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzYwNjEsIm5iZiI6MTcwNDQzNTc2MSwicGF0aCI6Ii8xMDgyMjEzLzI5NDQwODI3NS1jODFkOWVjMy0wNjI1LTRjYWUtOWEzMS0zNDJlYzAyYjlmMWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDVUMDYyMjQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWVjN2Y2MmRjMGE5ZWM4ZWU2OTZlZGJlNjhiNmFhNGJmN2YzMjRmY2ZiN2RjMjQ0ZDA5ODI3MTk1ZmY1NDAwNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jwvoEPwkG1XJac9UePFigpCo1GnI1FKD-W9_ZXNGC0I)
> 
> ..and choose `master` (**not** v3.3.4). Once downloaded, you will need to restart HA for the changes to take effect.

Thank you. Redownload helps

**Comment by AlexxIT** [comment] 2024-01-05 09:20
#1245

**Closed by AlexxIT** 2024-01-05 09:20 UTC
Labels: duplicate

**Comment by Mategm** [comment] 2024-01-05 12:26
> Go to [#1245 (comment)](https://github.com/AlexxIT/XiaomiGateway3/issues/1245#issuecomment-1876994323)
> 
> And run patch

Thank You! Its realy works!

**Comment by const2github** [comment] 2024-01-06 08:35
Confirm. Working. Thank you.
