### ISSUE TITLE
HA 2023.1 update: Unexpected exception importing platform custom_components.xiaomi_gateway3.climate

### ISSUE THREAD

**Issue by osnwt** [AlexxIT/XiaomiGateway3#904] opened 2023-01-04 21:52 UTC
After update to Home Assistant core 2023.1 the following error is shown:

```
2023-01-05 00:43:34.387 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.xiaomi_gateway3.climate
2023-01-05 00:43:34.389 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform xiaomi_gateway3.climate: Platform not found (Exception importing custom_components.xiaomi_gateway3.climate).

```

**Comment by randybb** [comment] 2023-01-04 22:26
duplicate of #899

**Comment by lysiong** [comment] 2023-01-05 00:59
same as mines, me on stable version of HA 2023.1 update.

**Comment by goxofy** [comment] 2023-01-05 02:10
same problem

**Comment by philtempleton** [comment] 2023-01-05 06:34
I'm also experiencing this issue since installing the HA 2023.1.0 update.
- Supervisor: 2022.12.1
- OS 9.4
- Frontend 20230104.1 - latest

**Closed** 2023-01-05 06:35 UTC
Labels: duplicate

**Comment by kismomesz** [comment] 2023-01-05 23:05
> I'm also experiencing this issue since installing the HA 2023.1.0 update.
> 
> * Supervisor: 2022.12.1
> * OS 9.4
> * Frontend 20230104.1 - latest

Same problem

**Comment by Lobo2022** [comment] 2023-01-10 11:39
Same problem

Home Assistant 2023.1.2
Interface: 20230104.0 - latest

**Comment by mashiahd** [comment] 2023-01-18 16:25
Same... any fix >?

**Comment by DJTerentjev** [comment] 2023-01-18 16:27
> Same... any fix >?

What is version of xiaomi_gateway3 integration?

**Comment by kismomesz** [comment] 2023-01-18 16:31
Already fixed, available in beta version.
